### ISSUE TITLE
Add an automatic version number

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#180]
Wouldn't it be nice if the script showed the version number when it ran? It would make user troubleshooting easier - and our own!

It would also be nice to integrate the version number properly when we start on a proper package deployment. 

I've started [the branch "version-numbering"](https://github.com/torbengb/bank2ynab/tree/version-numbering) to try to work on this.

I've now made code that works in Py2, but oddly Travis complains about Py3 while I can't reproduce that.

My version construction might seem a little roundabout, but I've integrated existing packages that are made for this purpose. 

- [ ] TODO: make the code pick up the version from the Git tag.

On top of that, I've added the basis of a version suffix so that we can see what branch the code came from. On the `master` branch, no suffix should be shown.

- [ ] TODO: make the code pick up the branch, and add it as suffix.

Further tasks to complete the proper configuration of `setup.py`:

- [x] rearrange the file structure according to [this guide](https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/creation.html#arranging-your-file-and-directory-structure).
- [ ] rename our `README.md` into `.srt` format as suggested in the same link.
- [x] note I started writing [this wiki page](https://github.com/torbengb/bank2ynab/wiki/PublishRelease) about details of the process.

**Comment by torbengb** [comment]
I wonder if I can parse the file `.git/FETCH_HEAD` because that contains the current branch. 

That's obviously only in the repo, not in the user's runtime. This is also true for the Git tags I guess? I haven't really understood how the packages I included figure this out.

**Comment by torbengb** [comment]
Huh, Travis fails on Py3.x but not on Py2. I can't figure out why.

**Comment by nocalla** [comment]
It's because your code fails the automatic style check. Version 2 isn't checked for style, but 3 is. Read the log for the build and look for "flake8" and you'll see what the errors are. Mostly whitespace errors from my quick look. 

```
The command "pip install flake8" exited with 0.
0.97s$ if [[ $TRAVIS_PYTHON_VERSION == 3* ]] && [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then flake8 --builtins=unicode; fi
./__init__.py:2:5: E221 multiple spaces before operator
./__init__.py:3:12: E221 multiple spaces before operator
./__init__.py:3:80: E501 line too long (137 > 79 characters)
./__init__.py:4:80: E501 line too long (137 > 79 characters)
./__init__.py:5:4: E221 multiple spaces before operator
./__init__.py:6:6: E221 multiple spaces before operator
./__init__.py:7:7: E221 multiple spaces before operator
./__init__.py:10:14: E221 multiple spaces before operator
./__init__.py:10:21: E261 at least two spaces before inline comment
./__init__.py:11:14: E221 multiple spaces before operator
./__init__.py:11:21: E261 at least two spaces before inline comment
./__init__.py:12:14: E221 multiple spaces before operator
./__init__.py:12:23: E261 at least two spaces before inline comment
./__init__.py:13:15: E221 multiple spaces before operator
./__init__.py:13:34: E261 at least two spaces before inline comment
./__init__.py:13:80: E501 line too long (95 > 79 characters)
./__init__.py:16:30: E701 multiple statements on one line (colon)
./__init__.py:18:24: E701 multiple statements on one line (colon)
./__version__.py:1:78: W291 trailing whitespace
./__version__.py:5:1: F401 '__init__.VERSION' imported but unused
./bank2ynab.py:27:1: F401 'version.get_version' imported but unused
./bank2ynab.py:28:1: F403 'from __init__ import *' used; unable to detect undefined names
./bank2ynab.py:535:11: F405 'NAME' may be undefined, or defined from star imports: __init__
./bank2ynab.py:535:24: F405 'VERSION' may be undefined, or defined from star imports: __init__
./setup.py:13:1: F401 'setuptools.find_packages' imported but unused
./setup.py:15:1: F403 'from __init__ import *' used; unable to detect undefined names
./setup.py:17:1: F401 'version.get_version' imported but unused
./setup.py:27:80: E501 line too long (81 > 79 characters)
./setup.py:32:80: E501 line too long (80 > 79 characters)
./setup.py:38:29: E261 at least two spaces before inline comment
./setup.py:38:30: E262 inline comment should start with '# '
./setup.py:38:36: W291 trailing whitespace
./setup.py:39:9: E128 continuation line under-indented for visual indent
./setup.py:68:80: E501 line too long (86 > 79 characters)
./setup.py:78:10: F405 'NAME' may be undefined, or defined from star imports: __init__
./setup.py:81:5: E265 block comment should start with '# '
./setup.py:82:17: F405 'DESCRIPTION' may be undefined, or defined from star imports: __init__
./setup.py:83:22: F405 'LONG_DESCRIPTION' may be undefined, or defined from star imports: __init__
./setup.py:84:12: F405 'AUTHOR' may be undefined, or defined from star imports: __init__
./setup.py:85:18: F405 'EMAIL' may be undefined, or defined from star imports: __init__
./setup.py:86:9: F405 'URL' may be undefined, or defined from star imports: __init__
./setup.py:89:17: F405 'NAME' may be undefined, or defined from star imports: __init__
./version.py:2:70: W291 trailing whitespace
```

**Comment by torbengb** [comment]
Thanks - my prettifying attempts were counterproductive, hah! Now that I've learned this log from you, I will work on getting rid of those messages.

**Comment by torbengb** [comment]
Wow, that code checker is *picky!* I think I've gotten rid of all the "E"rrors and the "W"arnings. I hope I don't need to bother about the "F"lake issues too.

Personally, I think the line limit of 78 chars is archaic and ridiculous, but I'll go with it.

**Comment by nocalla** [comment]
It goes by Python best practices. Allows easy readability without multiple warring standards. I wonder can I add some hook functionality to auto fix white space issues, since those are easy.

**Comment by nocalla** [comment]
I don't know about the Flake issues, I think any error makes Travis cry.

**Comment by torbengb** [comment]
Yep - I have fixed them all now, and Travis is happy again.

**Comment by nocalla** [comment]
Yay!

**Comment by torbengb** [comment]
Basic versioning is implemented in the branch `feature-176-pypi-installer` as part of #176.
I will keep this #180 open for the purpose of automating the tag and branch stuff.

**Comment by nejch** [comment]
Hi @torbengb, not sure how exactly you want to format this, but I think a lot of packages use something like `git describe --tags` to get the most recent tag from git. This will also add the number of commits since the tag and the current commit hash. Also check out `git describe --tags --dirty --always`.

You can then also get the current branch using `git rev-parse --abbrev-ref HEAD`. 

So you could get these with subprocess, just need to be careful as you may not always be checked out from git or have git installed etc.

[Here's](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/__init__.py#L56) an example that gets the current commit hash.

Or there's also stuff like this :)
https://pypi.org/project/setuptools_scm/
https://github.com/warner/python-versioneer

**Comment by torbengb** [comment]
Thank you @nejch for your input - much appreciated! I just haven't gotten around to GitHub lately...
