### ISSUE TITLE
1.2 marketing

### ISSUE THREAD

**Issue by torbengb** [bank2ynab/bank2ynab#265]
Seeing how fast you are progressing with the API support, we are moving ever closer to our 1.2 milestone. In my eyes that is a huge leap, and users should be made aware - and potential new users in particular. So I'll open this ticket as a brainstorm/checklist for 1.2 launch stuff.

I'm thinking obviously posting on the subreddit but also on the YNAB forum(?) and getting listed on the YNAB website. 

- posting on the subreddit https://www.reddit.com/r/ynab/
- posting on the YNAB forum
  - [ ] https://support.youneedabudget.com/category/announcements and
  - [ ] https://support.youneedabudget.com/category/importing and
  - [ ] https://support.youneedabudget.com/category/api
- getting listed on the YNAB website
  - [ ] Support page about CSV import: https://docs.youneedabudget.com/article/921-importing-a-csv-file
    - I'm particularly interested in getting us listed there because I truly believe our tool is better than the one(!) linked there now.
  - [ ] Works with YNAB: https://api.youneedabudget.com/#works-with-ynab
  - [ ] https://api.youneedabudget.com/#clients-community
- Social media?
  - [ ] twitter #ynab #ynabapi 
  - [ ] does anybody still use facebook?
- what else??

What else can we do to get 1.2 noticed? 

(edit: changed 2.0 to 1.2 as agreed below)

**Comment by duch11** [comment]
I find that a lot of potential users of this script would be less tech-savvy than us. 
Maybe we should consider making/using an installation script as a part of 2.0?

Alternatives would be nicely set up tutorial with pictures.
Maybe hosted on Github somehow? 
Or a place like medium.com?
Do we have the ability to make one of those pretty project websites?
I'm imagining something like this: http://gnomepomodoro.org/

**Comment by duch11** [comment]
I actually really like the approach he/she has taken with the converter, simple and hosted.
No installation, no fuss.. Just drag and drop.. 
Although we have more functionality, this project has nailed the UX.
I don't think it would be impossible to do the same with frameworks like Flask.
Site:
https://aniav.github.io/ynab-csv/
Source:
https://github.com/aniav/ynab-csv

**Comment by nocalla** [comment]
We can host a website on GitHub pages directly. It might be worth doing that in a separate repo in the organisation just to avoid cluttering this one. "Installation" falls under the Pypi installer. Maybe that would be worth targeting in v2.0.

**Comment by torbengb** [comment]
I agree with both of you. Our tool is neat but hard to set up, so the pypi
is just a first step.

Earlier today I had the idea that it would be awesome to built our tool
into a one-page website: just drag any CSAV file onto the web page and it
will detect the format, convert it into YNAB CSV format, and then upload
the file to your budget, and then all in one go. That is one step better
than the other tools out there now.

It only requires a small settings widget where a first-time user can enter
his API key, and perhaps select his favorite budget.

I used to be a webmaster, though my skills are a bit dated so all this
newfangled Angular and whatnot is new to me. Still, I'd be happy to provide
whatever I can in that regard. Including hosting, by the way!

**Comment by nocalla** [comment]
I think we're a bit off having an online converter. I'd suggest making that be 2.1 maybe as it's a new set of functionality so should be distinct. Or 3.0 since it does change the workflow compatibility somewhat as you'd need to drop files individually.

**Comment by nocalla** [comment]
Or even have the web version be a separate project that leverages this one as a backend?

**Comment by torbengb** [comment]
I agree, a website is an entirely different product, strictly speaking
off-topic for this marketing issue. Let's cut this idea off here, I'll open
a new ticket for it.

**Comment by torbengb** [comment]
New issue #266 created.

**Comment by torbengb** [comment]
@duch11 you mention an installer, and/or an online user guide. I agree with you that these are sorely needed, because our tool is currently very tech-oriented. Some of this has begun to be addressed but it's not completed yet:

We do have plans for an installer (see #176) and even that is just a first step because the user still needs to edit his user-config file, even potentially downloading and installing Python itself first!

Our documentation is currently a fairly long README.md plus some wiki pages, although the wiki is mostly aimed at contributors rather than users. I find the README reasonably good and complete but even so it's not very user-friendly.

We could easily create more *.md pages and interlink them, or extend the wiki to include end users, or even use GitHub Pages to build a pretty website. I'm all for it! Either or all of these steps would be great to have - and I feel it's something that **I** can contribute to this project, as I'm not really a programmer. I don't mean to grab this for myself though; every contribution is more than welcome.

I'll create tickets for some of these steps that we don't have yet, just so we have action points that we can track.

**Comment by nocalla** [comment]
@torbengb I'm more than happy for you to take on that workload! The pretty website would be a nice thing to aim for. I'll contribute what I can, of course, but work away!

**Comment by torbengb** [comment]
Following our convention to use semantic versioning, none of this warrants a 2.0 release number, as backward compatibility is maintained. So I've put this into 1.2 instead.

I'm thinking we should put the pretty website into 1.3 just to make sure it doesn't block us from releasing this _awesome_ API functionality - unless we feel that proper docs are a requirement for launching our API feature?

**Comment by nocalla** [comment]
Agreed - website for 1.3.

**Comment by duch11** [comment]
Sounds good to me! :)
