### ISSUE TITLE
Improve repo structure

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#345]
**Is your feature request related to a problem? Please describe.**
As per #176, certain changes are required to the repo to allow us to add our project to package managers like PyPi. Furthermore, it's getting a little confusing to navigate the project files, especially for new users.

**Describe the solution you'd like**
As per the references listed below, there are a few things that we need to do. I know that @torbengb was working on these as part of #176, but I'd like to take a stab at it in a more systematic fashion (no offence intended to @torbengb!) and integrate the changes to the structure before implementing #176.

- [x] Move our main project file into its own subdirectory
- [x] Move plugins package into `bank2ynab` as a subpackage
- [x] Amend references to script to point to package directory
- [x] Create `__init__.py`
- [x] Create `setup.py` (or focus on  `pyproject.toml` - research needed)
- [x] Split the code into more manageable modules
- [x] Investigate if we can move the Github templates to their own directory (?)
- [x] Add `MANIFEST.in`

**Describe alternatives you've considered**
Leave everything as-is and forget about making the project easier to install.

**Additional context**
https://github.com/navdeep-G/samplemod (example python project)
https://github.com/bast/somepackage (lots of references here)

**Comment by nocalla** [comment]
To investigate: do we need to specify bank2ynab.bank2ynab for imports in the plugins file or is bank2ynab sufficient? We have to do it for the tests, but they're in a separate directory to the main project.
